### ISSUE TITLE
404 Error for Valid Email Addresses

### ISSUE THREAD

**Issue by trevor-shinder** [epool/pikmail-api#5]
Hello, 

I'd like to report that over the last few days, pikmail has not returned a successful image/avatar for valid email addresses, rather it is returning a 404 error for all valid emails.  Is this a known issue?

Thank you,

**Comment by epool** [comment]
@trevor-shinder this is a known issue, I just updated the README section with this info, thanks for having used Pikmail.

# DEPRECATED

**UPDATE:**
Since this API was fully based on the [Picasa API](https://developers.google.com/picasa-web/) and that API has been depreated, Therefore this API is being deprecated too unless we found a workaround to this.

```
This API is being deprecated and will be turned down in January 2019. Migrate to Google Photos Library API as soon as possible to avoid disruptions to your application.
```

Info [Here](https://developers.google.com/picasa-web/)
